/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ISwipeEvent,
} from './utils/interface';

export namespace Components {
  interface SSwipe {
    'thresholdX': number;
    'thresholdY': number;
    'timeThreshold': number;
  }
}

declare global {


  interface HTMLSSwipeElement extends Components.SSwipe, HTMLStencilElement {}
  var HTMLSSwipeElement: {
    prototype: HTMLSSwipeElement;
    new (): HTMLSSwipeElement;
  };
  interface HTMLElementTagNameMap {
    's-swipe': HTMLSSwipeElement;
  }
}

declare namespace LocalJSX {
  interface SSwipe {
    'onSSwipe'?: (event: CustomEvent<ISwipeEvent>) => void;
    'thresholdX'?: number;
    'thresholdY'?: number;
    'timeThreshold'?: number;
  }

  interface IntrinsicElements {
    's-swipe': SSwipe;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      's-swipe': LocalJSX.SSwipe & JSXBase.HTMLAttributes<HTMLSSwipeElement>;
    }
  }
}


